### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by hopugop** [scylladb/cpp-driver#66]
Links from this page are broken:
https://cpp-driver.docs.scylladb.com/master/topics/index.html

Example:
`cass_cluster_set_num_threads_io()` shortcut points to a 404'd page: https://cpp-driver.docs.scylladb.com/master/api/struct.CassCluster/#function-cass_cluster_set_num_threads_io
There are many more on that page.

cc @annastuchlik

**Comment by annastuchlik** [comment]
@hopugop Thanks for reporting this problem!

@dgarcia360 None of the links to our API is working in the cpp-driver documentation. I THINK I know how to fix it, but I need you to confirm because I'm not sure how the linking mechanism works in this project.

 The links are configured to refer the user to the datastax API, for example:
[`CassFuture`]: http://datastax.github.io/cpp-driver/api/struct.CassFuture/
See https://raw.githubusercontent.com/scylladb/cpp-driver/master/topics/README.md.

But on the published page they look like links to the ScyallaDB API:
![image](https://user-images.githubusercontent.com/37244380/177977548-43496d29-e072-4b4e-95b8-4d1c1fa98977.png)

When you click the link, you get 404.

Solution:
Replace `datastax.github.io/cpp-driver` with `cpp-driver.docs.scylladb.com/master` in the URLs, for example:
[`CassFuture`]: https://cpp-driver.docs.scylladb.com/master/api/struct.CassFuture/
